# Generated by Django 4.1.5 on 2023-01-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='gerne',
            new_name='genre',
        ),
    ]
